<?php

namespace CarouselBundle\Repository;

use AppBundle\Repository\BaseRepository;

/**
 * CarouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarouselRepository extends BaseRepository
{

}
